# 1. Escolhe a imagem base (Python 3.11 leve)
FROM python:3.11-slim

# 2. Define variáveis de ambiente para o Python não travar logs e não criar arquivos .pyc
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 3. Instala dependências do sistema necessárias para o PostgreSQL (psycopg2)
# O 'gcc' e 'libpq-dev' são vitais para compilar o driver do banco
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    espeak \
    libespeak1 \
    && rm -rf /var/lib/apt/lists/*

# 4. Cria a pasta de trabalho dentro do container
WORKDIR /app

# 5. Copia a lista de ingredientes e instala
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 6. Copia todo o seu código para dentro do container
COPY . .

# 7. Comando padrão ao iniciar (Substitua pelo nome do seu arquivo principal)
# Como sua UI é interativa (Textual), vamos deixar apenas o python chamando o arquivo
CMD ["python", "jarvis_ui.py"]